apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/brianwcook/trusted-artifacts?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trusted-artifacts
    appstudio.openshift.io/component: my-component
    pipelines.appstudio.openshift.io/type: build
  name: my-component-on-push
  namespace: brianwcook-tenant
spec:
  params:
  - name: dockerfile
    value: Containerfile
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/brianwcook-tenant/trusted-artifacts/my-component:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: docker-build-multi-platform-oci-ta
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
